### ISSUE TITLE
 生年月日・性別部分を作成/HTML,CSS,JS/profile

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#10]
「Create～」ボタンを押す前の生年月日・性別の入力部分を作成してください

■要件

・「src/ejs/component/profile.ejs」内に
```
<div class="profile">
  <div class="profile__input"></div>
</div>
```
　を作成し、「profile__input」内部に適切なHTMLを記述してください。

・「src/sass/component/profile.scss」内に適切なCSSを記述してください。

・必要であれば「src/js/」内に.jsファイルを作成し記述してください

▼必要な機能

＞生年月日を入力する機能

＞♂♀をクリックすることで選択できるようにする機能（択一）

**Comment by mochimochimoon** [comment]
![profile](https://user-images.githubusercontent.com/37008369/37811741-3f88f116-2e9f-11e8-9787-639daea2d003.PNG)

**Comment by TagYut** [comment]
やりますね

**Comment by TagYut** [comment]
ソースがあまりに汚いので組み方が何か違う気がしてます。ひとまず仮組としてレイアウトのみ一応見られる形にしておきました。
後々ですが当該箇所のピクセルの厳密さ（もしくは求め方）を聞いたほうが良さそう。
