### ISSUE TITLE
headingコンポーネント(CSSのみ)の修正/CSS/"_heading.scss"

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#113]
headingコンポーネントのCSSの修正を行う

■要件
**※#103 のマージが完了してから作業を始めること**

・「src/sass/component/_heading.scss」に正しいSassを記述する

■修正内容
・同コンポーネントでの修正が見つかった場合、このIssueに書き込んでください。

**Comment by mochimochimoon** [comment]
■修正内容追加
・#81
・#86
・#90 
(作業＆マージが完了したら上記Issueに作業終了報告のコメントを書き込む)

**Comment by TagYut** [comment]
やりました

**Comment by TagYut** [comment]
修正点（_heading.scss）
・`top: 29.9px`を`30px`に
・`top:102px;`を`100px`に
