### ISSUE TITLE
create-btnコンポーネントの修正/HTML,CSS/"create-btn.ejs""_create-btn.scss"

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#116]
create-btnコンポーネントのHTML,CSSの修正を行う

■要件
※#103 のマージが完了してから作業を始めること

・「src/ejs/component/create-btn.ejs」に正しいejsを記述する
・「src/sass/component/_create-btn.scss」に正しいSassを記述する

■修正内容
・同コンポーネントでの修正が見つかった場合、このIssueに書き込んでください。

**Comment by mochimochimoon** [comment]
■修正内容追加
・#81
・#82 
(マージが完了したら上記Issueに作業終了報告のコメントを書き込む)

**Comment by TagYut** [comment]
やりました
