### ISSUE TITLE
footerコンポーネントの修正/HTML,CSS/"footer.ejs""_footer.scss"

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#118]
footerコンポーネントのHTML,CSSの修正を行う

■要件
※#103 のマージが完了してから作業を始めること

・「src/ejs/component/footer.ejs」に正しいejsを記述する
・「src/sass/component/_footer.scss」に正しいSassを記述する

■修正内容
・同コンポーネントでの修正が見つかった場合、このIssueに書き込んでください。

**Comment by mochimochimoon** [comment]
■修正内容追加
・#81
・#85 
(マージが完了したら上記Issueに作業終了報告のコメントを書き込む)

**Comment by TagYut** [comment]
やりました

**Comment by TagYut** [comment]
修正点：
・media query自体の削除（29pxから31pxへの変化だったので）
