### ISSUE TITLE
ページ最下部を作成/HTML,CSS,JS/footer

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#12]
ページ最下部（footer）を作成する

■要件
・「src/ejs/component/footer.ejs」内に
```<footer></footer>```
　を作成し、適切なHTMLを記述する。

・「src/sass/component/footer.scss」内に適切なCSSを記述する。

・必要であれば「src/js/」に.jsファイルを作成し記述する。

![footer](https://user-images.githubusercontent.com/37008369/37811888-01fa8700-2ea0-11e8-9c3f-6b0b743adc89.PNG)

**Comment by antyoku** [comment]
やります。
