### ISSUE TITLE
ページ読み込み時白くちらつく問題の修正/HTML,CSS,JS/"where.ejs""_where.scss""where.js"

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#145]
#99 

■要件
・「src/ejs/component/where.ejs」に正しいejsを記述する
・「src/sass/component/_where.scss」に正しいscssを記述する
・「src/js/where.js」に正しいJSを記述する

**Comment by antyoku** [comment]
やります。
