### ISSUE TITLE
都道府県選択用のoption（一番上）が空である問題/HTML/"where.ejs"

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#151]
都道府県を選択する```<select>```の```<option>```を修正する。

■要件
・「src/ejs/component/where.ejs」に正しい記述を行う

■修正点
・空の```<option>```は「HTML Validator」でエラーとしてはじかれてしまうので修正する

・最終的に```index.html```が「HTML Validator」を正常に通るようにする。

**Comment by antyoku** [comment]
自分の担当部分なのでやります
