### ISSUE TITLE
デザインがボコボコになっている

### ISSUE THREAD

**Issue by deerboy** [Update-hub/stage-2-team-mochimochi#160]
<img width="360" alt="2018-04-11 18 35 26" src="https://user-images.githubusercontent.com/5842851/38608752-32ba2b7c-3db7-11e8-85e2-e708aacdbd95.png">

仕様では各セレクタの間がフラットな見た目になっている。現状各セレクタに角丸があるので見た目がボコボコしている

**Comment by TagYut** [comment]
対応しています
