### ISSUE TITLE
where are you～部分を作成/HTML,CSS,JS/where

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#17]
ページ読み込み時点（Create～ボタンを押す前）のwhere部分を作成する

■要件

・「src/ejs/component/where.ejs」内に```<div class="where"></div>```を作成し、適切なHTMLを記述する。

・「src/sass/component/where.scss」内に適切なCSSを記述しする。

・必要であれば「src/js/」内に.jsファイルを作成し記述する

▼必要な機能

＞heading.ejsをincludeする機能。
　（引数に適切な値を入力する）

＞現在地（都道府県）を入力できる機能

＞入力した内容を元にGoogleMapを表示する機能（設定は https://github.com/Update-hub/stage-2-team-mochimochi/wiki を参照）

![where](https://user-images.githubusercontent.com/37008369/37871775-af6dd008-3031-11e8-943e-69d2f1197cd2.PNG)

**Comment by antyoku** [comment]
やります。

**Comment by antyoku** [comment]
heading.ejsの方で入力欄のtypeがtextに固定されてますが、仕様にある都道府県セレクタというのは、自由入力でなくて都道府県をリストから選べるようにしたほうがいいでしょうか？

**Comment by mochimochimoon** [comment]
たしかに要件に都道府県セレクタと書いてありますね。見落としてました。
想定外の入力を避けるという意味で、「セレクタでリストから選ぶ」という形をとった方が安全だと思います。

もし```<input>```から```<select>```にするなら、
```include()```関連の部分を消して、
```<div class="heading">～</div>```を直接書き込んで対応していただいて大丈夫です。（class名は再現して欲しいです）

**Comment by antyoku** [comment]
了解です。
