### ISSUE TITLE
～your favorite～部分を作成/HTML,CSS,JS/favorite

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#18]
ページ読み込み時点（Create～ボタンを押す前）のfavorite部分を作成してください。

■要件
・「src/ejs/component/favorite.ejs」内に```<div class="favorite"></div>```を作成し、適切なHTML,ejsを記述してください。

・「src/sass/component/favorite.scss」内に適切なCSSを記述してください。

・必要であれば「src/js/」内に.jsファイルを作成し記述してください

▼必要な機能

＞heading.ejsをincludeする機能。
　（引数に適切な値を入力する。）

＞入力した内容を元にYouTubeを表示する機能

![favorite](https://user-images.githubusercontent.com/37008369/37871880-ecc78d7a-3033-11e8-8e7b-04b2ab2d22b3.PNG)

**Comment by antyoku** [comment]
やります。
