### ISSUE TITLE
inputタグにフォントを適用する/CSS

### ISSUE THREAD

**Issue by TagYut** [Update-hub/stage-2-team-mochimochi#26]
仕様上、common.scssで指定したとしても、inputタグにはフォント設定は継承されないです。inputだけはfont-weightもfont-familyも適用されていない。
それを防ぐためには各種のinputタグ部に親要素の継承を示す`inherit`プロパティを指定するのが良さそうかな、という気がしてます。
ただ正直これは細部の調整なので、別issueを立てて後々修正するぐらいの優先度ですね。

`font-family: inherit;`
`font-weight: inherit;`

**Comment by mochimochimoon** [comment]
へぇ～なるほど。継承されないんですねぇ。
後々別の修正とまとめてIssue出すので一旦この件は預かります。
