### ISSUE TITLE
where～部分の出力機能を作成/HTML,CSS,JS/where

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#29]
引数を元に地図を出力する機能を関数として定義する

■要件
・「src/js/」に「output-where.js」を作成し
```function outputWhere(～){～}```
　で関数を定義する。

・必要であれば「src/ejs/component/where.ejs」にHTML,ejsを記述する

・必要であれば「src/sass/component/where.scss」内にCSSを記述する。

▼必要な機能
・outputWhere()関数はページ読み込み時に「output-core.js」内のコードから呼び出されて使用されます（URLにパラメータがある時のみ）

・outputWhere()関数は第一引数に'Tokyo''Chiba'などの文字列（地名）を渡して使います。
　```outputWhere('Tokyo')```のように使います。

・outputWhere()関数を実行すると引数を元にして地図が表示された状態になる。（画像参照）

・最終的にoutputWhere()関数は定義だけする。実行はしない。
![o-where-m](https://user-images.githubusercontent.com/37008369/38015901-433a1526-32a8-11e8-880e-5820681fc7f0.JPG)
![o-where](https://user-images.githubusercontent.com/37008369/38015902-44346ddc-32a8-11e8-8a21-b56bef11c799.JPG)

**Comment by antyoku** [comment]
やります。
