### ISSUE TITLE
favorite出力画面と機能を作成/HTML,CSS,JS/favorite

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#37]
ページ読み込み時に動画を出力する機能を関数として定義する

■要件
・「src/js/」に.jsファイルを作成し
```function outputFavorite(～)｛～｝```
　で関数を定義する。

・必要であれば「src/ejs/component/favorite.ejs」に適切なHTMLを記述する

・必要であれば「src/sass/component/favorite.scss」内に適切なCSSを記述する。

▼必要な機能
・outputFavorite()関数は第一引数にURL（文字列）が与えられます
　```outputFavorite('https://～')```のように使います。

・outputWhere()関数が実行すると引数を元にした動画が表示され、入力欄が消えて画像のような画面になる。

・outputWhere()関数は実行せずに定義だけする。
![default](https://user-images.githubusercontent.com/37008369/38184201-1c4007be-3681-11e8-9f4e-ff40ededf30b.JPG)

**Comment by antyoku** [comment]
やります
