### ISSUE TITLE
【バグ】profileのインプットがmaleにしかならない問題/JS/create-btn.js

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#54]
ラジオボタンが♂♀どちらを選んでもURLにgender=maleが渡されてしまう問題を修正する。

■要件
・「create-btn.js」の記述を修正し、不具合を解消する。

■補足情報
・```<input type="radio">```がチェックされているかを判定する機能に不具合があります。
11,13行目にある
```$('#female').val() === 'on'```
などが誤った記述だと思われます。

**Comment by antyoku** [comment]
これもやります。
