### ISSUE TITLE
【バグ】男性を選んだ時に表示されるランプの数が合わない問題/JS/output-profile.js

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#55]
♂を選んで結果を出力した時に、表示されるランプの数が１つ多い不具合を修正する。

■要件
・「output-profile.js」の記述を修正し、不具合を解消する。

■補足情報
・おそらく33行目の```var i = config.lifeSpanMale + 1```が原因なのではないかと思われます。

**Comment by antyoku** [comment]
やります
