### ISSUE TITLE
fontを継承させる/HTML,CSS/profile,what,where,favorite,heading.scss

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#60]
```<input><select><option>```などフォーム系の要素は一部のブラウザでフォント系のCSSが親要素から継承されないようです。
なので、継承されていないCSSを継承してください。

■要件
・「profile」「what」「where」「favorite」「heading」などのejsおよびscssでフォーム要素にfont-family,font-weightなどを```inherit```させるように記述を行う

**Comment by TagYut** [comment]
やります
