### ISSUE TITLE
 favorite movie?の入力欄の初期値を設定する/HTML/favorite.ejs

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#67]
favorite movie?の入力欄の```<input>```に入力すべき内容（youtubeのURL）がわかりやすいように初期値を設定する

■要件
・「src/ejs/component/favorite.ejs」内に正しいHTMLを記述する

■機能
・記述する初期値については以下の項目を念頭におく
　●初期値は入力例の様なかたちの方が良さそう？
　●「youtubeのURLを入力する」ことがわかりやすいように
　●favorite.jsの処理次第ですが、なるべく初期値では動画が読み込まれないように
　
・他の処理にバグが発生しないように注意して作業する。
　もし、バグが必ず発生してしまう場合はIssueおよびチームに報告を上げて作業を中止してください。

**Comment by antyoku** [comment]
そしてやります

**Comment by TagYut** [comment]
やっておこうかと思いましたが、よくよく考えてみると同じ理由で職業欄にも「エンジニア」とかあらかじめ書いておいたほうが良いような気もして…おっと、先を越されてしまった

**Comment by TagYut** [comment]
ああ、でもこれ別に職業に限らないですね。何者ですか？と聞かれて「何者でもない」とか答えても底は別に個人のLifecardなので問題ないしかえってそのほうがいいのか。自己完結してしまった。
なんでもなかったです、忘れてください
