### ISSUE TITLE
コンポーネント「heading.scss」の改善/CSS/heading.scss

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#70]
heading.scssの修正を行う。

■要件
・「src/sass/component/heading.scss」を修正する

■修正点

・色情報をHexに統一する
・font-family,font-weightを削除（inherit除く）
・```.heading```の横paddingを45pxに統一

・その他修正箇所があれば、修正してかまいません。

**Comment by TagYut** [comment]
やります、ました。
