### ISSUE TITLE
【CC】editorconfig修正

### ISSUE THREAD

**Issue by deerboy** [Update-hub/stage-2-team-mochimochi#78]
https://github.com/Update-hub/stage-2-team-mochimochi/blob/85935257aa7c0db209ee7dd91ac045e65b0a1ac6/.editorconfig#L9

両方 true が良い（詳細はググる）

trim_trailing_whitespace = false
insert_final_newline = false

**Comment by antyoku** [comment]
修正作業が完了したので閉じます。
