### ISSUE TITLE
ページ全体のCSSを設定/CSS/common.scss

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#8]
ページ全体にかかるCSSを設定する

■要件

・「src/sass/component/common.scss」内に
　画面全体(html,bodyなど)にかかるCSSを記述する

**Comment by TagYut** [comment]
背景色（ブラック）はここで指定してもいいかもしれないですね。
それから色指定ですが、rgbaよりも#三文字で指定したほうがほんの少し文字数が減る気がしますがどうでしょうか。

before `background-color: rgba(17, 17, 17, 1);`
after `background-color: #111;`

雀の涙ですね…

**Comment by TagYut** [comment]
すでに指摘ありましたが、フォントの指定もここでするなら早いところ common.scss は組み込んだほうが良さそうなので、取り急ぎ担当します。

**Comment by antyoku** [comment]
common以外での背景色の指定は削ってしまったほうが良いでしょうか。

**Comment by TagYut** [comment]
そのほうが軽量化できる気がしています。`background-color: #000`はいろんなところで使っているので、動作に問題がなければ全部消しちゃってよさそう

**Comment by TagYut** [comment]
ひとまず背景色とフォントだけ指定したcommon.scssを作成しました。weightが100である理由は全体で見てThinではない場所が一個しかないからです。（Create my Life Cardボタンのみbold）
他に全体指定がふさわしいものがあるかどうか一旦意見を募ります。

**Comment by TagYut** [comment]
24時間経ちましたが他に必要そうなものも浮かばなかったので、この状態でpull requestを飛ばします。
頻出する文字色や背景色・`text-align: center;`等の大体全部にかかるstyleなど、あとで思いついたら都度対応するのでこのissueをreopenしてください。
