### ISSUE TITLE
【CC】media query の mixin化

### ISSUE THREAD

**Issue by deerboy** [Update-hub/stage-2-team-mochimochi#81]
https://github.com/Update-hub/stage-2-team-mochimochi/blob/85935257aa7c0db209ee7dd91ac045e65b0a1ac6/src/sass/component/common.scss#L14

何回も出てきて助長なのでmixin化できるとなおよし

media query  mixin などでググる

**Comment by mochimochimoon** [comment]
メディアクエリをmixin化しました。
今後メディアクエリは
```
  @media screen and (min-width: 600px){
      background-color: yellow;
  }
```
↓
```
  @include screen-min($breakpoint){
      background-color: yellow;
  }
```
のように使えます
