### ISSUE TITLE
【CC】modifire じゃダメだろうか 

### ISSUE THREAD

**Issue by deerboy** [Update-hub/stage-2-team-mochimochi#84]
favorite-btn のなかに .focus という割とグローバルかつ汎用的なクラスがいるのが違和感。
他のInput やセレクタで使おうとした時競合する恐れあり。
favocite-btn にひもづく固有のものであれば、 favorite-btn--focus などとし、厳密に紐付けると良いかと

https://github.com/Update-hub/stage-2-team-mochimochi/blob/85935257aa7c0db209ee7dd91ac045e65b0a1ac6/src/sass/component/favorite.scss#L59

**Comment by mochimochimoon** [comment]
#115 の作業・マージしました。
修正完了したのでcloseします。
