### ISSUE TITLE
【CC】.headingが重複

### ISSUE THREAD

**Issue by deerboy** [Update-hub/stage-2-team-mochimochi#86]
https://github.com/Update-hub/stage-2-team-mochimochi/blob/0095d839cd1917db0d5e3f1f2934c9a5f582cb5b/src/sass/component/heading.scss#L1

レイアウトで分ける記法が馴染みなく、多くの現場で突っ込まれるの必須なので一つのスコープにまとめたい。（明確な理由と意図があればレスください）

**Comment by mochimochimoon** [comment]
#113 作業・マージ終了しました。
修正完了とみなしてcloseします。
