### ISSUE TITLE
【CC】1000ms = 1s

### ISSUE THREAD

**Issue by deerboy** [Update-hub/stage-2-team-mochimochi#87]
https://github.com/Update-hub/stage-2-team-mochimochi/blob/0095d839cd1917db0d5e3f1f2934c9a5f582cb5b/src/sass/component/output-profile.scss#L64

1s と書くのが一般的。どっちでもいいけどタイプ量が少なく、ファイル容量も減るので理由がなければ1sが良い

**Comment by mochimochimoon** [comment]
#112 マージ完了しました。
作業終了と判断してcloseします。
