### ISSUE TITLE
【CC】code style 調整

### ISSUE THREAD

**Issue by deerboy** [Update-hub/stage-2-team-mochimochi#88]
https://github.com/Update-hub/stage-2-team-mochimochi/blob/0095d839cd1917db0d5e3f1f2934c9a5f582cb5b/src/sass/component/tweet.scss#L2

format かけたい。（波括弧がくっついている）

**Comment by mochimochimoon** [comment]
#117 の作業完了しました。
修正完了したとみなしてcloseします
