### ISSUE TITLE
メイン画像（ブラックパンサー）部分を作成/HTML,CSS,JS/hero

### ISSUE THREAD

**Issue by mochimochimoon** [Update-hub/stage-2-team-mochimochi#9]
ページ上部の画像(ブラックパンサー)部分を作成してください

■要件

・「src/ejs/component/hero.ejs」内に
```
<div class="hero"></div>
```
　を作成し、適切なHTMLを記述する。

・「src/sass/component/hero.scss」内に適切なCSSを記述する。

・必要であれば「src/js/」内に.jsファイルを作成し記述してください

**Comment by mochimochimoon** [comment]
![hero](https://user-images.githubusercontent.com/37008369/37811703-203fda18-2e9f-11e8-890e-bd164a0e9421.PNG)

参考画像です

**Comment by antyoku** [comment]
担当します
