### ISSUE TITLE
【CC】heading の modifirer なので heading のscssに置きたい

### ISSUE THREAD

**Issue by deerboy** [Update-hub/stage-2-team-mochimochi#90]
https://github.com/Update-hub/stage-2-team-mochimochi/blob/0095d839cd1917db0d5e3f1f2934c9a5f582cb5b/src/sass/component/where.scss#L13

**Comment by mochimochimoon** [comment]
#113 #114 作業・マージ終了しました。
修正完了とみなしてcloseします。
