### ISSUE TITLE
【CC】output-favorite.js の最適化

### ISSUE THREAD

**Issue by deerboy** [Update-hub/stage-2-team-mochimochi#94]
https://github.com/Update-hub/stage-2-team-mochimochi/blob/0095d839cd1917db0d5e3f1f2934c9a5f582cb5b/src/js/output-favorite.js#L2

セミコロンあるがESLint 走っているかな？

下記は省略可能。ダブルクウォーとがあるのも惜しい
```
var output = document.getElementById('outputMovie');
  output.innerHTML = "<div class
```

```
$('#outputMovie').html('<div...')
```

**Comment by TagYut** [comment]
#155 で解決されたとみてCloseします
