### ISSUE TITLE
【CC】むやみにファイル分割、関数化をしない

### ISSUE THREAD

**Issue by deerboy** [Update-hub/stage-2-team-mochimochi#95]
https://github.com/Update-hub/stage-2-team-mochimochi/blob/0095d839cd1917db0d5e3f1f2934c9a5f582cb5b/src/js/output-tweet.js#L3

ファイル分割を多用するとコードリーディング時に追うのが大変なので、この規模のコードは利用シーンでワンラインで使えるのでファイル分割、関数化は避けたい

**Comment by TagYut** [comment]
#121 で修正されたと判断してCloseします。
