### ISSUE TITLE
【CC】JS 全体的な統一

### ISSUE THREAD

**Issue by deerboy** [Update-hub/stage-2-team-mochimochi#97]
この辺がブレているので全体的に統一したい

- 即時関数で囲まれているファイルとそうでないファイル
- ダブルクウォート使われているファイル
- format かかっていないファイル、ESLint通っていないファイル
- jQuery の DOM キャッシュと バニラJSの Element 指定の混在（こちらはまあこのままでも良い）
- use strict あるファイル、ないファイル

**Comment by mochimochimoon** [comment]
今回のチーム制作では

・.jsファイル内の記述を即時関数```(function(){  ～  })()```で囲む
（変数の競合が怖いので）
・文字列リテラルを表すのは'シングルクォート'
・formatをかける
・ESLintエラーが出ないように
（ESLintに従った結果、index.jsに結合した際に問題が発生するなら、結合時の整合性を優先してエラーは無視する）
（$やgoogleなどが定義されていない問題はhttps://docs.update.jp/dokyumento/ji-chu-zhi-shi/eslint）
・なるべくjQuery の DOM キャッシュでelementを指定して処理を行う
・```'use strict'```は記述しない

に統一したいと思います。
この統一は暫定的なもので問題・ご意見があれば、随時募集中です。

**Comment by deerboy** [comment]
> ESLintエラーは無視してください

ESconfig でセミコロン必須にすると良いかなーと。

クリティカルな問題はないので閉じます。
