### ISSUE TITLE
【CC】tweet.js 最適化

### ISSUE THREAD

**Issue by deerboy** [Update-hub/stage-2-team-mochimochi#98]
https://github.com/Update-hub/stage-2-team-mochimochi/blob/0095d839cd1917db0d5e3f1f2934c9a5f582cb5b/src/js/tweet.js#L22

関数かするほどの規模でないので関数化しなくても良いかも（重箱レベルなので余裕があればで良い）

**Comment by mochimochimoon** [comment]
#122 作業終了・マージしました。
修正完了とみなしてcloseします。
