### ISSUE TITLE
【CC】一瞬白くちらつく

### ISSUE THREAD

**Issue by deerboy** [Update-hub/stage-2-team-mochimochi#99]
初期表示時、画面下部が一瞬白くちらつく（chrome）

**Comment by antyoku** [comment]
このちらつきというのはおそらくマップの読み込みのことで、これに関しては最上部にある画像が正常に表示されるようになれば「ページ表示時にちらつく」という見え方にはならないと思うのですがどうでしょう……

**Comment by mochimochimoon** [comment]
「スクロールした状態でリロード」「マップ読み込みが遅れてその間にスクロールしてしまった」
などの場合、画像が正常に表示されてもマップの読み込みのちらつきが見えてしまうと思います。なので、できれば修正したほうが良さそうです。

もし修正がJS以外にも及ぶようなら、ちらつきの修正は後回しにして別Issue立てて修正を行いたいのでどこかでリアクションください。

**Comment by antyoku** [comment]
JS内だけで解決するのはちょっと難しそうです。

**Comment by mochimochimoon** [comment]
ではこの件はそのうち別Issue立てます。
なので、ちらつきの件は一旦忘れてもらって大丈夫です。

**Comment by mochimochimoon** [comment]
#145 作業・マージ終了しました。
修正完了とみなしcloseします。
